### ISSUE TITLE
idempotent swarm_labels

### ISSUE THREAD

**Issue by oppianmatt** [atosatto/ansible-dockerswarm#27]
When using this and reapplying, even if the labels haven't changed they get removed and readded. Meaning any docker instances targeted with the labels get removed and readded for a loss of service.

A small change would make them idempotent. This code here it will remove labels no longer in the list, and add any that aren't already set.

```
- name: Remove labels from swarm node
  command: docker node update --label-rm {{ item }} {{ inventory_hostname }}
  with_items: "{{ docker_swarm_labels.stdout_lines }}"
  when: item not in swarm_labels
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  delegate_facts: True
  tags:
    - skip_ansible_lint
    - swarm_labels

- name: Asign labels to swarm nodes | if any
  command: docker node update --label-add {{ item }}=true {{ inventory_hostname }}
  when: item not in docker_swarm_labels.stdout_lines
  with_items:
    - "{{ swarm_labels  | default([]) }}"
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  delegate_facts: True
  tags:
    - skip_ansible_lint
    - swarm_labels
```
