### ISSUE TITLE
Adding Group Names as Swarm_Labels

### ISSUE THREAD

**Issue by ricalenil** [atosatto/ansible-dockerswarm#35]
Maybe this could be helpful for someone.

Add this at the top of swarm_cluster.yml to set group_names as swarm labels for each swarm_node.

```
---
- name: "Set SWARM LABELS"
  set_fact: swarm_labels="{{ group_names }}"
  tags:
    - skip_ansible_lint
    - swarm_labels
```
