### ISSUE TITLE
Enable support for Raspberry Pi

### ISSUE THREAD

**Issue by wombathuffer** [atosatto/ansible-dockerswarm#77]
Thanks for refactoring the code - your doing a great job here!

I'm using your role on a pi3, so I have a few modifications, I would ask you to add?

1. Could you please add `armv7l: "arm64"` to `docker_architechture` in `vars/main.yml` ?

2. Could you add the following to the bottom of tasks/setup-docker-compose.yml ?
```
  when: ansible_userspace_architecture is defined 
- block:
  - name: Pip install Docker Compose.
    pip:
      name: docker-compose
      extra_args: --user
      executable: pip3

  when: ansible_userspace_architecture is undefined
```
This enables docker compose to be installed via pip on my type device. :)

Thank you!!
